"""
Constantes pour le module de gestion des commandes.
"""

# Statuts de commande
ORDER_STATUS_DRAFT = "DRAFT"
ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_CONFIRMED = "CONFIRMED"
ORDER_STATUS_PROCESSING = "PROCESSING"
ORDER_STATUS_SHIPPED = "SHIPPED"
ORDER_STATUS_DELIVERED = "DELIVERED"
ORDER_STATUS_CANCELLED = "CANCELLED"
ORDER_STATUS_REFUNDED = "REFUNDED"

# Types de paiement
PAYMENT_TYPE_CARD = "CARD"
PAYMENT_TYPE_TRANSFER = "TRANSFER"
PAYMENT_TYPE_CHECK = "CHECK"
PAYMENT_TYPE_CASH = "CASH"

# Statuts de paiement
PAYMENT_STATUS_PENDING = "PENDING"
PAYMENT_STATUS_COMPLETED = "COMPLETED"
PAYMENT_STATUS_FAILED = "FAILED"
PAYMENT_STATUS_REFUNDED = "REFUNDED"

# Messages d'erreur
ERROR_ORDER_NOT_FOUND = "Commande non trouvée"
ERROR_INVALID_ORDER_STATUS = "Statut de commande invalide"
ERROR_PAYMENT_FAILED = "Échec du paiement"
ERROR_INSUFFICIENT_STOCK = "Stock insuffisant pour la commande"

# Limites
MAX_ORDER_ITEMS = 50
MIN_ORDER_AMOUNT = 0.01
MAX_ORDER_AMOUNT = 10000.00 